swagger: "2.0"
info:
  version: "0.0.1"
  title: Mesh Up
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_driver
    get:
      description: Returns 'Hello' to the driver
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the driver
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /stream:
    # binds a127 app logic to a route
    x-swagger-router-controller: stream
    put:
      description: Sets the vehicle location
      # used as the method name of the controller
      operationId: setvehiclelocation
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/Location'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      description: Gets vehicle stream
      # used as the method name of the controller
      operationId: getstreamvehicle
      parameters:
        - name: name
          in: query
          description: vehicle id
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/NetworkResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Broadcast message to the network
      # used as the method name of the controller
      operationId: sendvehiclemsg
      parameters:
         - name: body
           in: body
           required: true
           schema:
            $ref: '#/definitions/Message'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /vehicle:
    # binds a127 app logic to a route
    x-swagger-router-controller: vehicle
    get:
      description: Returns the vehicle properties
      # used as the method name of the controller
      operationId: vehicle
      parameters:
        - name: id
          in: query
          description: The id of the vehicle
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/VehicleResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Suggests another route
      # used as the method name of the controller
      operationId: runaway
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/Suggestion'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/VehicleSuggestionResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /event:
    # binds a127 app logic to a route
    x-swagger-router-controller: event
    get:
      description: Returns the network state
      # used as the method name of the controller
      operationId: getevents
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/NetworkResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Broadcast a network event
      # used as the method name of the controller
      operationId: postevent
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/Event'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/NetworkResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  VehicleResponse:
    type: object
  VehicleSuggestionResponse:
    required:
      - message
    properties:
      message:
        type: string
  NetworkResponse:
    type: array
    items:
      type: object
  Event:
    type: object
    properties:
      vehicle:
        description: vehicle id (ONLY LETTERS & UPPER CASE)
        type: string
      lat:
        description: latitude
        type: number
      lon:
        description: longitude
        type: number
      msg:
        description: message
        type: string
    example:
        vehicle: ONE
        lat: 50.817000
        lon: -74.006400
        msg: 'Airbag: OMG, I just released!'
  Suggestion:
    type: object
    properties:
      suggestion:
        description: what?
        type: string
      vehicle:
        description: which vehicle
        type: integer
  Message:
    type: object
    properties:
      vehicle:
        description: vehicle id
        type: string
      content:
        description: message
        type: string
      location:
        description: location
        type: object
    example:
      vehicle: car_1
      content: "Breaks: Nailed it!! From 100 to 0 in 3s"
      location:
          lat: 40.717000
          lon: -74.006400
  Location:
    type: object
    properties:
      vehicle:
        description: vehicle id
        type: string
      location:
        description: location
        type: object
        properties:
          lat:
            description: latitude
            type: number
          lon:
            description: longitude
            type: number
    example:
      vehicle: car_1
      location:
          lat: 40.717000
          lon: -74.006400
